### PR TITLE
Pruning files from old repo

### PR DESCRIPTION
**Pull request by mumichae**
Some files in this repo don't belong to the pipeline or aren't used any more, so they are removed here.

- [x] `scripts/preprocessing.py` --> reproducibility
- [x] `scripts/run_normalize.sh` --> reproducibility
- [x] `scripts/sim_norm,py` --> reproducibility
- [x] `environment.yaml`--> remove
- [x] `scripts/metrics/makefile` --> to scib
- [x] `scripts/cc_score*`--> remove
- [x] `scripts/scale_halfopen` --> remove

Corresponding PRs:
- scib: https://github.com/theislab/scib/pull/217
- scib-reproducibility: https://github.com/theislab/scib-reproducibility/pull/4

### CODE REVIEW

**Comment by mumichae** [comment]
@lazappi Some preprocessing files (see above) need to be moved to reproducibility, as they are used before the pipeline is run.

@danielStrobl Can you confirm that these files are exclusively used outside of the pipeline?

**Comment by lazappi** [comment]
> @lazappi Some preprocessing files (see above) need to be moved to reproducibility, as they are used before the pipeline is run.

Do you want to start a PR to add them to `scib-reproducibility`? I would suggest we do that first before deleting them from here.

**Comment by mumichae** [comment]
Good idea, I have now created a branch for adding these scripts to `scib-reproducibility` called [cleanup](https://github.com/theislab/scib-reproducibility/tree/cleanup).

**Review by LuckyMD — APPROVED** [review]
Nice! Even updated the figure :).

**Pull request merged**
